name: run-producer

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      topic: 
        required: true
        type: string

jobs:

  run-producer:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run Kafka client app unit test
        run: |
          docker run -t -e TOPIC=${{ inputs.topic }} \
                        -v ${DEST_WORKSPACE}/${{ inputs.config }}:/etc/librdkafka.config \
                        --name my-python-app --rm ghcr.io/ybyzek/python-app:latest \
                        bash -c 'echo "topic: $TOPIC" && /usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
