name: 'Run Confluent cp-all-in-one'
description: 'Setup Confluent cp-all-in-one'
author: 'ybyzek'
inputs:
  github branch version:
    description: 'GitHub branch of cp-all-in-one to use'
    required: false
    default: 'latest'
  service:
    description: 'Up to which service to bring up'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
