name: 'Run Confluent cp-all-in-one'
description: 'Setup Confluent cp-all-in-one'
author: 'ybyzek'
inputs:
  github branch version:
    description: 'GitHub branch of cp-all-in-one to use'
    required: false
    default: 'latest'
  service:
    description: 'Define service up to which to start'
    required: false
    default: ''
  project:
    description: 'docker project name used to set network name'
    required: false
    default: 'default'
runs:
  using: 'docker'
  image: 'Dockerfile'
