name: github-action-client-local

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      TOPIC: test3

    steps:

      - uses: actions/checkout@v2

      - name: Build Docker image for Kafka client app
        run: docker build --build-arg CONFIG=librdkafka.local.config --build-arg TOPIC=$TOPIC -t python-app .

      - name: Start Kafka
        run: docker-compose up -d

      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Run Kafka client app
        run: docker run -t --net kafka-github-actions_default --name my-python-app --rm python-app || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - name: Test message count
        run: tests/local.sh $TOPIC
