name: github-action-client-local
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/start-cp
      - uses: actions/run-producer
      - uses: actions/run-consumer
