name: kafka-app-2

on: 
  workflow_run:
    workflows: [kafka-app]
    types: [completed]

env:
  # General
  DEST_WORKSPACE: ${{ github.workspace }}
  NETWORK: workspace_default
  TOPIC: t3
  CONFLUENT_BOOTSTRAP_SERVERS: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
  CONFLUENT_API_KEY: ${{ secrets.CONFLUENT_API_KEY }}
  CONFLUENT_API_SECRET: ${{ secrets.CONFLUENT_API_SECRET }}
  # Confluent Cloud Schema Registry and AVRO
  TOPICAVRO: t3-avro
  CONFLUENT_SCHEMA_REGISTRY_URL: ${{ secrets.CONFLUENT_SCHEMA_REGISTRY_URL }}
  CONFLUENT_BASIC_AUTH_USER_INFO: ${{ secrets.CONFLUENT_BASIC_AUTH_USER_INFO }}

jobs:

  unit-2:

    needs: build

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - uses: actions/checkout@v2

      - name: Run Kafka client app unit test
        run: |
          docker run -t -e TOPIC=$TOPIC \
                       -v ${DEST_WORKSPACE}/configs/librdkafka.unit.config:/etc/librdkafka.config \
                        --name my-kafka-app --rm ghcr.io/${{ github.actor }}/kafka-app:latest \
                        bash -c '/usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
