name: run-producer

env:
  DEST_WORKSPACE: ${{ github.workspace }}

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      topic: 
        required: true
        type: string

jobs:

  run-producer:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Run Kafka client app unit test
        run: |
          docker run -t -e TOPIC=${{inputs.topic}} \
                        -v ${DEST_WORKSPACE}/configs/${{inputs.config}}:/etc/librdkafka.config \
                        --name my-python-app --rm ghcr.io/${{ github.actor }}/python-app:latest \
                        bash -c 'echo "topic: $TOPIC" && echo "topic2: ${{inputs.topic}}" && echo "config: ${{ inputs.config }}" && /usr/bin/producer.py -f /etc/librdkafka.config -t $TOPIC'
